name: Publish RELEASE

on:
  release:
    types: [published]

jobs:
  test:
    if: "!github.event.release.prerelease"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
      - run: | 
          npm install
          npm run build
          npm run test

  build-publish:
    if: "!github.event.release.prerelease"
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
          registry-url: https://registry.npmjs.org/
      - run: | 
          npm install
          npm run build
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NODE_TKN}}
