name: Publish DEV

on:
  push:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
      - run: | 
          npm i
          npm run build
          npm run test

  build-publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm
          registry-url: https://registry.npmjs.org/
      - run: |
          npm i
          npm run build
          npm publish --access public --tag dev
        env:
          NODE_AUTH_TOKEN: ${{secrets.NODE_TKN}}
