name: Publish DEV

on:
  release:
    types: [published]

jobs:
  test:
    if: github.event.release.prereleased == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: | 
          npm install
          npm run build
          npm run test

  build-publish:
    if: github.event.release.prereleased == true
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - run: | 
          npm install
          npm run build
          npm publish --access public --tag dev
        env:
          NODE_AUTH_TOKEN: ${{secrets.NODE_TKN}}
