name: BETA Publish

on:
  release:
      branches:
       - dev
      types:
       - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: | 
          npm install
          npm run build
          npm run test

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - run: | 
          npm install
          npm run build
          npm publish --access public --tag beta
        env:
          NODE_AUTH_TOKEN: ${{secrets.NODE_TKN}}