name: Publish BETA

on:
  push:
      branches:
       - dev

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: | 
          npm install
          npm run build
          npm run test